# -*- coding: utf-8 -*-
"""FIN_MODEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sfx-hoxVR5blwXGoK6wfiPXrAacwi-c6
"""

import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers
from sklearn.preprocessing import MinMaxScaler

# ------------------------------------------------------------------------------
# 1. CONFIGURATION & HYPERPARAMETERS
# ------------------------------------------------------------------------------
# NEW DATA PATHS
DATA_PATH = "/kaggle/input/datasets/kankshitha2808/multiclass-parquet-dataset"
TRAIN_FILE = os.path.join(DATA_PATH, "final_train_multiclass.parquet")
TEST_FILE = os.path.join(DATA_PATH, "final_test_multiclass.parquet")

WINDOW_SIZE = 10
D_MODEL = 128
NUM_HEADS = 4

NUM_CLIENTS = 6
NUM_ROUNDS = 50
BATCH_SIZE = 512
BASE_LR = 1e-3
SIMULATE_HIJACKED = True

GAMMA = 0.99
EPSILON_START = 1.0
EPSILON_END = 0.05
EPSILON_DECAY = 0.92

# --- NEW: Active Learning Action Space ---
# 0 = Allow, 1 = Rate-Limit, 2 = Drop, 3 = Request Label (Active Learning)
NUM_ACTIONS = 4

NUM_CLASSES_T1 = 6
NUM_CLASSES_T2 = 19
BENIGN_IDX_T1 = 0

label_remapping = {
    0: 0, 1: 1, 2: 2, 3: 2, 4: 3, 5: 3, 6: 4, 7: 5, 8: 5, 9: 5,
    10: 5, 11: 2, 12: 2, 13: 2, 14: 2, 15: 3, 16: 3, 17: 3, 18: 3
}

features_to_keep = [
    'Header_Length', 'Protocol Type', 'Duration', 'IPv', 'LLC',
    'fin_flag_number', 'syn_flag_number', 'rst_flag_number',
    'psh_flag_number', 'ack_flag_number', 'ece_flag_number', 'cwr_flag_number',
    'ack_count', 'syn_count', 'fin_count', 'rst_count', 'HTTP', 'HTTPS', 'DNS',
    'Telnet', 'SMTP', 'SSH', 'IRC', 'TCP', 'UDP', 'DHCP', 'ARP', 'ICMP', 'IGMP',
    'Rate', 'Srate', 'Drate', 'Tot sum', 'Min', 'Max', 'AVG', 'Std',
    'Tot size', 'IAT', 'Number', 'Radius', 'Covariance', 'Variance', 'Weight'
]

# ------------------------------------------------------------------------------
# 2. DATA LOADING & PREPROCESSING
# ------------------------------------------------------------------------------
def load_and_preprocess_parquet(file_path):
    print(f"Loading data from {file_path}...")
    df = pd.read_parquet(file_path, engine='pyarrow')
    df = df.fillna(df.median(numeric_only=True))

    # Create Labels
    y2 = df['label'].astype(int).values
    y1 = np.vectorize(label_remapping.get)(y2)
    y_bin = (y1 > 0).astype(np.int32) # 0 = Benign, 1 = Attack
    y2 = np.where(y1 == BENIGN_IDX_T1, -1, y2) # Mask T2 benign

    # Task 3: Intensity (Scaled to 0-1 and masked for Benign)
    y3_raw = df['Magnitue'].fillna(0.0).values.reshape(-1, 1)
    y3 = MinMaxScaler().fit_transform(y3_raw).flatten().astype(np.float32)
    y3 = np.where(y1 == BENIGN_IDX_T1, 0.0, y3)

    # Scale Features
    scaler = MinMaxScaler()
    X = scaler.fit_transform(df[features_to_keep].values.astype(np.float32))

    return X, y_bin, y1, y2, y3

train_X, train_y_bin, train_y1, train_y2, train_y3 = load_and_preprocess_parquet(TRAIN_FILE)

def create_client_datasets(X, y_bin, y1, y2, y3, num_clients, window_size, batch_size):
    print("Generating Synchronized Time-Series Client Datasets...")
    client_datasets = []
    chunk_size = len(X) // num_clients

    for i in range(num_clients):
        start_idx = i * chunk_size
        end_idx = (i + 1) * chunk_size if i < num_clients - 1 else len(X)

        Xc = X[start_idx:end_idx]
        # Align labels to the LAST element of the window
        yc_bin = y_bin[start_idx:end_idx]
        yc1 = y1[start_idx:end_idx]
        yc2 = y2[start_idx:end_idx]
        yc3 = y3[start_idx:end_idx]

        # Use the built-in target parameter to keep X and Y synced
        ds = tf.keras.utils.timeseries_dataset_from_array(
            data=Xc,
            targets=np.stack([yc_bin, yc1, yc2, yc3], axis=1),
            sequence_length=window_size,
            sequence_stride=1,
            shuffle=False,
            batch_size=batch_size
        )

        client_datasets.append(ds.prefetch(tf.data.AUTOTUNE))

    return client_datasets

import tensorflow as tf
from tensorflow.keras import layers

def build_refined_defense_model(input_shape, num_actions):
    inputs = layers.Input(shape=input_shape)

    # Stream 1: Temporal (Conv1D + MultiHead Attention)
    x1 = layers.Conv1D(64, kernel_size=3, padding='same', activation='relu')(inputs)
    attn_out = layers.MultiHeadAttention(num_heads=4, key_dim=16)(x1, x1)
    x1 = layers.GlobalAveragePooling1D()(attn_out)

    # Stream 2: SAE — reduced L1 from 0.05 → 0.005 to avoid zero-predictor trap
    x2 = layers.TimeDistributed(layers.Dense(32, activation='relu'))(inputs)
    latent = layers.TimeDistributed(
        layers.Dense(8, activation='relu',
                     activity_regularizer=tf.keras.regularizers.l1(0.005))
    )(x2)

    # Decoder for Reconstruction
    x_dec = layers.TimeDistributed(layers.Dense(32, activation='relu'))(latent)
    reconstructed = layers.TimeDistributed(
        layers.Dense(input_shape[1], activation='sigmoid'), name='sae_reconstruction'
    )(x_dec)

    state_repr_sae = layers.Flatten()(latent)
    combined = layers.Concatenate()([x1, state_repr_sae])
    dense_shared = layers.Dense(128, activation='relu')(combined)

    # ── Task-specific neck layers ──────────────────────────────────────────────
    # Each head gets its own private pathway so objectives don't conflict
    dqn_neck = layers.Dense(64, activation='relu')(dense_shared)
    t1_neck  = layers.Dense(64, activation='relu')(dense_shared)
    t2_neck  = layers.Dense(128, activation='relu')(dense_shared)  # larger: 19-class is hardest
    t3_neck  = layers.Dense(32,  activation='relu')(dense_shared)

    # ── Output heads ──────────────────────────────────────────────────────────
    q_values = layers.Dense(num_actions, name='dqn_action')(dqn_neck)
    t1_out   = layers.Dense(6,  activation='softmax', name='t1_type')(t1_neck)
    t2_out   = layers.Dense(19, activation='softmax', name='t2_subtype')(t2_neck)
    t3_out   = layers.Dense(1,  activation='sigmoid', name='t3_intensity')(t3_neck)
    # sigmoid on T3 keeps predictions in [0,1] matching the MinMaxScaler target range

    return tf.keras.Model(
        inputs=inputs,
        outputs=[q_values, t1_out, t2_out, t3_out, reconstructed]
    )

# ------------------------------------------------------------------------------
# 5. REFINED COST-SENSITIVE REWARD FUNCTION
# ------------------------------------------------------------------------------
@tf.function
def get_reward_tf(actions, labels):
    """
    Actions: 0 (Allow), 1 (Rate-Limit), 2 (Drop), 3 (Request Label - Active Learning)
    """
    actions, labels = tf.cast(actions, tf.int32), tf.cast(labels, tf.int32)

    # Reward mapping if True Label is an Attack (1)
    # Heavy penalty for Allow (False Negative), Reward for Drop (True Positive)
    attack_rewards = tf.where(actions == 0, -150.0,
                        tf.where(actions == 1, 10.0,
                            tf.where(actions == 2, 50.0, -0.05))) # -0.05 is the Active Learning cost

    # Reward mapping if True Label is Benign (0)
    # Reward for Allow, Reduced penalty for Rate-Limit, Penalty for Drop (False Positive)
    benign_rewards = tf.where(actions == 0, 10.0,
                        tf.where(actions == 1, -2.0,
                            tf.where(actions == 2, -20.0, -0.05)))

    return tf.where(labels == 1, attack_rewards, benign_rewards)

# ── LOSS WEIGHTS ───────────────────────────────────────────────────────────────
# DQN already scaled by *0.01 internally, so 0.5 here is still meaningful.
# T3 MSE operates on [0,1] values — raw loss is tiny, so weight must be higher
# than intuition suggests to avoid the "always predict 0" lazy solution.
W_DQN = 0.5
W_T1  = 0.8
W_T2  = 1.0
W_T3  = 0.3
W_SAE = 0.05

# ── SUPERVISED WARM-UP ────────────────────────────────────────────────────────
# Run this BEFORE the FL loop to give T1/T2/T3 heads a clean start,
# so early random RL actions don't corrupt classification gradients.
def pretrain_supervised(model, dataset, epochs=5, lr=1e-3):
    optimizer = tf.keras.optimizers.Adam(learning_rate=lr)
    print(f"  Pre-training supervised heads for {epochs} epochs...")
    for epoch in range(epochs):
        total_loss, batches = 0.0, 0
        for states, targets in dataset:
            y1 = tf.cast(targets[:, 1], tf.int32)
            y2 = tf.cast(targets[:, 2], tf.int32)
            y3 = tf.cast(targets[:, 3], tf.float32)

            with tf.GradientTape() as tape:
                _, p1, p2, p3, _ = model(states, training=True)

                loss_t1 = tf.reduce_mean(
                    tf.keras.losses.sparse_categorical_crossentropy(y1, p1))

                valid_mask = tf.not_equal(y2, -1)
                loss_t2 = tf.cond(
                    tf.reduce_any(valid_mask),
                    lambda: tf.reduce_mean(
                        tf.keras.losses.sparse_categorical_crossentropy(
                            tf.boolean_mask(y2, valid_mask),
                            tf.boolean_mask(p2, valid_mask))),
                    lambda: tf.constant(0.0)
                )

                # Attack-only T3: only compute regression loss on attack windows
                attack_mask_t3 = tf.not_equal(y3, 0.0)
                loss_t3 = tf.cond(
                    tf.reduce_any(attack_mask_t3),
                    lambda: tf.reduce_mean(
                        tf.square(tf.boolean_mask(y3, attack_mask_t3) -
                                  tf.squeeze(tf.boolean_mask(p3, attack_mask_t3), axis=1))),
                    lambda: tf.constant(0.0)
                )

                loss = (W_T1 * loss_t1) + (W_T2 * loss_t2) + (W_T3 * loss_t3)

            grads = tape.gradient(loss, model.trainable_variables)
            optimizer.apply_gradients(zip(grads, model.trainable_variables))
            total_loss += loss.numpy()
            batches += 1

        print(f"    Warm-up epoch {epoch+1}/{epochs} — loss: {total_loss/max(1,batches):.4f}")


# ── RL TRAIN STEP ─────────────────────────────────────────────────────────────
def create_client_train_step(model, target_model, optimizer):
    @tf.function
    def train_rl_step(states, targets, epsilon):
        y_bin = targets[:, 0]
        y1    = tf.cast(targets[:, 1], tf.int32)
        y2    = tf.cast(targets[:, 2], tf.int32)
        y3    = tf.cast(targets[:, 3], tf.float32)

        batch_size = tf.shape(states)[0]
        q_preds, _, _, _, _ = model(states, training=False)

        # Epsilon-Greedy action selection
        rand_vals      = tf.random.uniform([batch_size])
        random_actions = tf.random.uniform([batch_size], minval=0,
                                           maxval=NUM_ACTIONS, dtype=tf.int32)
        greedy_actions = tf.cast(tf.argmax(q_preds, axis=1), tf.int32)
        actions        = tf.where(rand_vals < epsilon, random_actions, greedy_actions)

        rewards = get_reward_tf(actions, y_bin)

        # Bellman target
        next_q_preds, _, _, _, _ = target_model(states, training=False)
        max_next_q   = tf.reduce_max(next_q_preds, axis=1)
        target_q_vals = tf.stop_gradient(
            tf.cast(rewards + GAMMA * max_next_q, tf.float32))

        with tf.GradientTape() as tape:
            q_values, p1, p2, p3, sae_recon = model(states, training=True)

            # DQN loss (already small due to *0.01)
            masks    = tf.one_hot(actions, NUM_ACTIONS)
            q_action = tf.reduce_sum(q_values * masks, axis=1)
            loss_dqn = tf.reduce_mean(tf.square(target_q_vals - q_action)) * 0.01

            # T1 loss
            loss_t1 = tf.reduce_mean(
                tf.keras.losses.sparse_categorical_crossentropy(y1, p1))

            # T2 loss — attack windows only
            valid_mask = tf.not_equal(y2, -1)
            loss_t2 = tf.cond(
                tf.reduce_any(valid_mask),
                lambda: tf.reduce_mean(
                    tf.keras.losses.sparse_categorical_crossentropy(
                        tf.boolean_mask(y2, valid_mask),
                        tf.boolean_mask(p2, valid_mask))),
                lambda: tf.constant(0.0)
            )

            # T3 loss — attack windows only (avoids zero-predictor reward on benign)
            attack_mask_t3 = tf.not_equal(y3, 0.0)
            loss_t3 = tf.cond(
                tf.reduce_any(attack_mask_t3),
                lambda: tf.reduce_mean(
                    tf.square(tf.boolean_mask(y3, attack_mask_t3) -
                              tf.squeeze(tf.boolean_mask(p3, attack_mask_t3), axis=1))),
                lambda: tf.constant(0.0)
            )

            # SAE reconstruction loss
            states_f32 = tf.cast(states, tf.float32)
            loss_sae   = tf.reduce_mean(tf.square(states_f32 - sae_recon))

            total_loss = (W_DQN * loss_dqn) + (W_T1 * loss_t1) + \
                         (W_T2 * loss_t2) + (W_T3 * loss_t3) + (W_SAE * loss_sae)

        grads = tape.gradient(total_loss, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))

        return loss_dqn, tf.reduce_mean(rewards)

    return train_rl_step

def robust_multi_krum_aggregation(weight_list, num_clients, num_malicious, multi_krum_m):
    # 1. Flatten nested model weights into 1D vectors for distance math
    flat_weights = [np.concatenate([w.flatten() for w in client_w]) for client_w in weight_list]
    flat_weights = np.array(flat_weights)

    num_to_keep = num_clients - num_malicious - 2
    scores = []

    # 2. Calculate distances to find honest clients
    for i in range(num_clients):
        distances = np.sum((flat_weights - flat_weights[i])**2, axis=1)
        closest_distances = np.sort(distances)[1:num_to_keep + 1]
        scores.append(np.sum(closest_distances))

    # 3. Select 'm' best clients and average them
    best_indices = np.argsort(scores)[:multi_krum_m]
    avg_flat_weight = np.mean(flat_weights[best_indices], axis=0)

    # 4. Reshape back into original model structure
    new_weights = []
    ptr = 0
    for template_w in weight_list[0]:
        size = np.prod(template_w.shape)
        new_weights.append(avg_flat_weight[ptr:ptr + size].reshape(template_w.shape))
        ptr += size

    return new_weights

# ── FEDERATED HELPERS ─────────────────────────────────────────────────────────
def get_global_weights(model, layer_indices):
    weights = []
    for idx in layer_indices:
        weights.extend(model.layers[idx].get_weights())
    return weights

def set_global_weights(model, layer_indices, new_weights):
    w_idx = 0
    for l_idx in layer_indices:
        layer = model.layers[l_idx]
        num_weights = len(layer.weights)
        layer.set_weights(new_weights[w_idx : w_idx + num_weights])
        w_idx += num_weights

# # ── INITIALIZE ────────────────────────────────────────────────────────────────
# INPUT_SHAPE = (WINDOW_SIZE, len(features_to_keep))

# client_models     = [build_refined_defense_model(INPUT_SHAPE, NUM_ACTIONS) for _ in range(NUM_CLIENTS)]
# target_models     = [build_refined_defense_model(INPUT_SHAPE, NUM_ACTIONS) for _ in range(NUM_CLIENTS)]
# client_optimizers = [tf.keras.optimizers.Adam(learning_rate=BASE_LR) for _ in range(NUM_CLIENTS)]
# client_train_steps = [
#     create_client_train_step(cm, tm, opt)
#     for cm, tm, opt in zip(client_models, target_models, client_optimizers)
# ]

# # Shared layers = everything except the 4 task-specific heads
# global_layer_indices = [
#     i for i, l in enumerate(client_models[0].layers)
#     if all(h not in l.name for h in
#            ['dqn_action', 't1_type', 't2_subtype', 't3_intensity']) and l.weights
# ]

# # ── FL LOOP ───────────────────────────────────────────────────────────────────
# def run_personalized_federated_simulation(num_rounds, clients_ds):
#     print("\n🔥 Phase 1: Supervised warm-up (all clients)...")
#     for i, (cm, ds) in enumerate(zip(client_models, clients_ds)):
#         print(f"  Client {i+1}/{NUM_CLIENTS}")
#         pretrain_supervised(cm, ds, epochs=5)

#     # After warm-up, sync all client backbones so they start FL from the same point
#     ref_weights = get_global_weights(client_models[0], global_layer_indices)
#     for cm, tm in zip(client_models, target_models):
#         set_global_weights(cm, global_layer_indices, ref_weights)
#         set_global_weights(tm, global_layer_indices, ref_weights)
#     print("✅ Warm-up complete — backbones synced across all clients.\n")

#     print("🚀 Phase 2: Federated RL loop...")
#     current_epsilon = EPSILON_START
#     history = {'global_loss': [], 'global_reward': []}

#     for rnd in range(num_rounds):
#         actual_round = rnd + 1
#         print(f"\n=== Round {actual_round}/{num_rounds} ===")
#         local_weights  = []
#         round_rewards, round_losses = [], []

#         for i, ds in enumerate(clients_ds):
#             cm       = client_models[i]
#             train_fn = client_train_steps[i]
#             c_loss, c_reward, batches = 0.0, 0.0, 0

#             for b_states, b_targets in ds:
#                 loss, reward = train_fn(b_states, b_targets, current_epsilon)
#                 c_loss   += loss.numpy()
#                 c_reward += reward.numpy()
#                 batches  += 1

#             client_avg_loss = c_loss / max(1, batches)
#             client_avg_reward = c_reward / max(1, batches)

#             round_losses.append(client_avg_loss)
#             round_rewards.append(client_avg_reward)

#             w = get_global_weights(cm, global_layer_indices)

#             # Simulate Byzantine client (last client)
#             if SIMULATE_HIJACKED and i == NUM_CLIENTS - 1:
#                 w = [lw + np.random.normal(0, 2.0, lw.shape) for lw in w]

#             local_weights.append(w)

#             # --- Added requested print statement ---
#             print(f"  -> Client {i+1} done | Local Loss: {client_avg_loss:.4f} | Local Reward: {client_avg_reward:.2f}")

#         # Aggregate with robust Multi-Krum
#         print("  -> Aggregating weights via Multi-Krum...")
#         new_w = robust_multi_krum_aggregation(local_weights, NUM_CLIENTS, 1, 3)

#         for cm, tm in zip(client_models, target_models):
#             set_global_weights(cm, global_layer_indices, new_w)
#             set_global_weights(tm, global_layer_indices, new_w)

#         avg_l, avg_r = np.mean(round_losses), np.mean(round_rewards)
#         print(f"✅ Round {actual_round} Completed | Global Loss: {avg_l:.4f} | Global Reward: {avg_r:.2f} | Epsilon: {current_epsilon:.2f}")

#         # Checkpoint: Save all models every 10 rounds
#         if actual_round % 10 == 0:
#             print(f"💾 Saving Checkpoints for Round {actual_round}...")
#             for idx in range(NUM_CLIENTS):
#                 client_models[idx].save(f"/kaggle/working/checkpoint_round_{actual_round}_client_{idx+1}.keras")

#         history['global_loss'].append(avg_l)
#         history['global_reward'].append(avg_r)

#         current_epsilon = max(EPSILON_END, current_epsilon * EPSILON_DECAY)

#     print("\n✅ Federated RL Completed!")
#     print("🎉 Saving EVERYTHING (All Clients & Targets)...")

#     # ---------------------------------------------------------
#     # NEW: Literally saving everything (All 6 Clients + Targets)
#     # ---------------------------------------------------------
#     for i in range(NUM_CLIENTS):
#         c_path = f"/kaggle/working/final_client_{i+1}_model.keras"
#         t_path = f"/kaggle/working/final_target_{i+1}_model.keras"

#         client_models[i].save(c_path)
#         target_models[i].save(t_path)
#         print(f"  💾 Saved Client {i+1} -> {c_path}")

#     print("✅ All individual models safely saved to /kaggle/working/!")
#     return history

# # ── EXECUTION ─────────────────────────────────────────────────────────────────
# import pandas as pd, json

# client_ds_list = create_client_datasets(
#     train_X, train_y_bin, train_y1, train_y2, train_y3,
#     NUM_CLIENTS, WINDOW_SIZE, BATCH_SIZE
# )

# final_history = run_personalized_federated_simulation(NUM_ROUNDS, client_ds_list)

# history_df = pd.DataFrame(final_history)
# history_df.index.name = 'Round'
# history_df.to_csv("/kaggle/working/robust_frl_training_logs.csv")

# safe_history = {k: [float(v) for v in vals] for k, vals in final_history.items()}
# with open("/kaggle/working/robust_frl_training_logs.json", "w") as f:
#     json.dump(safe_history, f, indent=4)
# print("📝 Training logs saved.")

# ── 1. INITIALIZE EMPTY MODELS FIRST ──────────────────────────────────────────
print("🏗️ Building empty model architectures...")
INPUT_SHAPE = (WINDOW_SIZE, len(features_to_keep))

client_models     = [build_refined_defense_model(INPUT_SHAPE, NUM_ACTIONS) for _ in range(NUM_CLIENTS)]
target_models     = [build_refined_defense_model(INPUT_SHAPE, NUM_ACTIONS) for _ in range(NUM_CLIENTS)]
client_optimizers = [tf.keras.optimizers.Adam(learning_rate=BASE_LR) for _ in range(NUM_CLIENTS)]
client_train_steps = [
    create_client_train_step(cm, tm, opt)
    for cm, tm, opt in zip(client_models, target_models, client_optimizers)
]

# Shared layers = everything except the 4 task-specific heads
global_layer_indices = [
    i for i, l in enumerate(client_models[0].layers)
    if all(h not in l.name for h in
           ['dqn_action', 't1_type', 't2_subtype', 't3_intensity']) and l.weights
]
print("✅ Architectures built in memory.")

# ── 2. NOW LOAD THE ROUND 40 WEIGHTS ──────────────────────────────────────────
# I updated the path below based on the output you shared
CHECKPOINT_DIR = "/kaggle/input/datasets/kankshitha2808/till-40"

print("\n📥 Loading Round 40 weights into all 6 clients and target models...")
for i in range(NUM_CLIENTS):
    ckpt_path = f"{CHECKPOINT_DIR}/checkpoint_round_40_client_{i+1}.keras"
    print(f"  -> Loading {ckpt_path}")

    # Load the saved model to extract weights
    saved_model = tf.keras.models.load_model(ckpt_path, compile=False)
    saved_weights = saved_model.get_weights()

    # Sync these trained weights into the active loop models
    client_models[i].set_weights(saved_weights)
    target_models[i].set_weights(saved_weights)

print("✅ All clients successfully synced with Round 40 knowledge.\n")

# ── RESUME INITIALIZATION ─────────────────────────────────────────────────────
CHECKPOINT_DIR = "/kaggle/input/datasets/kankshitha2808/till-40" # ⚠️ UPDATE THIS PATH

print("\n📥 Loading Round 40 weights into all 6 clients and target models...")
for i in range(NUM_CLIENTS):
    ckpt_path = f"{CHECKPOINT_DIR}/checkpoint_round_40_client_{i+1}.keras"
    print(f"  -> Loading {ckpt_path}")

    # Load the saved model to extract weights
    saved_model = tf.keras.models.load_model(ckpt_path, compile=False)
    saved_weights = saved_model.get_weights()

    # Sync these trained weights into the active loop models
    client_models[i].set_weights(saved_weights)
    target_models[i].set_weights(saved_weights)

print("✅ All clients successfully synced with Round 40 knowledge.\n")

# ── RESUME FL LOOP ────────────────────────────────────────────────────────────
def resume_personalized_federated_simulation(num_extra_rounds, clients_ds):
    print("🚀 Phase 2: Resuming Federated RL loop...")

    # Lock Epsilon to 0.05 to prevent random actions (RL Amnesia)
    current_epsilon = 0.05
    history = {'global_loss': [], 'global_reward': []}

    for rnd in range(num_extra_rounds):
        # Shift the round counter so it prints Round 41, Round 42, etc.
        actual_round = rnd + 41
        print(f"\n=== Round {actual_round}/50 ===")
        local_weights  = []
        round_rewards, round_losses = [], []

        for i, ds in enumerate(clients_ds):
            cm       = client_models[i]
            train_fn = client_train_steps[i]
            c_loss, c_reward, batches = 0.0, 0.0, 0

            for b_states, b_targets in ds:
                loss, reward = train_fn(b_states, b_targets, current_epsilon)
                c_loss   += loss.numpy()
                c_reward += reward.numpy()
                batches  += 1

            client_avg_loss = c_loss / max(1, batches)
            client_avg_reward = c_reward / max(1, batches)

            round_losses.append(client_avg_loss)
            round_rewards.append(client_avg_reward)

            w = get_global_weights(cm, global_layer_indices)

            # Simulate Byzantine client (last client)
            if SIMULATE_HIJACKED and i == NUM_CLIENTS - 1:
                w = [lw + np.random.normal(0, 2.0, lw.shape) for lw in w]

            local_weights.append(w)

            print(f"  -> Client {i+1} done | Local Loss: {client_avg_loss:.4f} | Local Reward: {client_avg_reward:.2f}")

        # Aggregate with robust Multi-Krum
        print("  -> Aggregating weights via Multi-Krum...")
        new_w = robust_multi_krum_aggregation(local_weights, NUM_CLIENTS, 1, 3)

        for cm, tm in zip(client_models, target_models):
            set_global_weights(cm, global_layer_indices, new_w)
            set_global_weights(tm, global_layer_indices, new_w)

        avg_l, avg_r = np.mean(round_losses), np.mean(round_rewards)
        print(f"✅ Round {actual_round} Completed | Global Loss: {avg_l:.4f} | Global Reward: {avg_r:.2f} | Epsilon: {current_epsilon:.2f}")

        # Checkpoint: Save all models for round 50
        if actual_round % 10 == 0:
            print(f"💾 Saving Checkpoints for Round {actual_round}...")
            for idx in range(NUM_CLIENTS):
                client_models[idx].save(f"/kaggle/working/checkpoint_round_{actual_round}_client_{idx+1}.keras")

        history['global_loss'].append(avg_l)
        history['global_reward'].append(avg_r)

    print("\n✅ Extended Federated RL Completed!")
    print("🎉 Saving EVERYTHING (All Clients & Targets)...")

    for i in range(NUM_CLIENTS):
        c_path = f"/kaggle/working/final_client_{i+1}_model_50_rounds.keras"
        t_path = f"/kaggle/working/final_target_{i+1}_model_50_rounds.keras"

        client_models[i].save(c_path)
        target_models[i].save(t_path)
        print(f"  💾 Saved Client {i+1} -> {c_path}")

    print("✅ All individual models safely saved to /kaggle/working/!")
    return history

# ── EXECUTION ─────────────────────────────────────────────────────────────────
import pandas as pd, json

client_ds_list = create_client_datasets(
    train_X, train_y_bin, train_y1, train_y2, train_y3,
    NUM_CLIENTS, WINDOW_SIZE, BATCH_SIZE
)

# Run for 10 extra rounds to reach round 50
EXTRA_ROUNDS = 10
final_history = resume_personalized_federated_simulation(EXTRA_ROUNDS, client_ds_list)

history_df = pd.DataFrame(final_history)
history_df.index = range(41, 51) # Adjust index for the CSV
history_df.index.name = 'Round'
history_df.to_csv("/kaggle/working/robust_frl_training_logs_rounds_41_to_50.csv")

safe_history = {k: [float(v) for v in vals] for k, vals in final_history.items()}
with open("/kaggle/working/robust_frl_training_logs_rounds_41_to_50.json", "w") as f:
    json.dump(safe_history, f, indent=4)
print("📝 Extended training logs saved.")

import os
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

# ------------------------------------------------------------------------------
# 1. CONFIGURATION & DATA LOADING
# ------------------------------------------------------------------------------
# ⚠️ UPDATE THIS PATH to the Kaggle folder holding your 50-round model files
MODEL_DIR = "/kaggle/input/datasets/kankshitha2808/till-50"

TEST_FILE = "/kaggle/input/datasets/kankshitha2808/multiclass-parquet-dataset/final_test_multiclass.parquet"
TRAIN_FILE = "/kaggle/input/datasets/kankshitha2808/multiclass-parquet-dataset/final_train_multiclass.parquet"

WINDOW_SIZE = 10
BATCH_SIZE = 512
BENIGN_IDX_T1 = 0

label_remapping = {
    0: 0, 1: 1, 2: 2, 3: 2, 4: 3, 5: 3, 6: 4, 7: 5, 8: 5, 9: 5,
    10: 5, 11: 2, 12: 2, 13: 2, 14: 2, 15: 3, 16: 3, 17: 3, 18: 3
}

features_to_keep = [
    'Header_Length', 'Protocol Type', 'Duration', 'IPv', 'LLC',
    'fin_flag_number', 'syn_flag_number', 'rst_flag_number',
    'psh_flag_number', 'ack_flag_number', 'ece_flag_number', 'cwr_flag_number',
    'ack_count', 'syn_count', 'fin_count', 'rst_count', 'HTTP', 'HTTPS', 'DNS',
    'Telnet', 'SMTP', 'SSH', 'IRC', 'TCP', 'UDP', 'DHCP', 'ARP', 'ICMP', 'IGMP',
    'Rate', 'Srate', 'Drate', 'Tot sum', 'Min', 'Max', 'AVG', 'Std',
    'Tot size', 'IAT', 'Number', 'Radius', 'Covariance', 'Variance', 'Weight'
]

print("Loading data from Parquet files...")
df_test = pd.read_parquet(TEST_FILE, engine='pyarrow').ffill().fillna(0)

# Process Labels
y2_raw = df_test['label'].astype(int).values
test_y1 = np.vectorize(label_remapping.get)(y2_raw)
test_y_bin = (test_y1 > 0).astype(np.int32)
test_y2 = np.where(test_y1 == BENIGN_IDX_T1, -1, y2_raw)
y3_raw = df_test['Magnitue'].fillna(0.0).values.reshape(-1, 1)
test_y3 = MinMaxScaler().fit_transform(y3_raw).flatten().astype(np.float32)
test_y3 = np.where(test_y1 == BENIGN_IDX_T1, 0.0, test_y3)

# Process Features
scaler = MinMaxScaler()
test_X = scaler.fit_transform(df_test[features_to_keep].values.astype(np.float32))

print("Generating Time-Series Windows...")
test_states = tf.keras.utils.timeseries_dataset_from_array(
    test_X, None, sequence_length=WINDOW_SIZE, batch_size=BATCH_SIZE
)

aligned_true_bin = test_y_bin[WINDOW_SIZE - 1:]
aligned_y1 = test_y1[WINDOW_SIZE - 1:]
aligned_y2 = test_y2[WINDOW_SIZE - 1:]
aligned_y3 = test_y3[WINDOW_SIZE - 1:]
print("✅ Data Ready.")

from sklearn.metrics import confusion_matrix, mean_squared_error, accuracy_score, precision_score, recall_score, f1_score, classification_report

# ⚠️ We evaluate Client 1 here as our baseline
MODEL_FILE = os.path.join(MODEL_DIR, "checkpoint_round_50_client_1.keras")

print(f"\n🚀 Loading Client 1 Model: {MODEL_FILE}")
final_model = tf.keras.models.load_model(MODEL_FILE, compile=False)
q_preds, t1_preds, t2_preds, t3_preds, sae_preds = final_model.predict(test_states)

pred_y1 = np.argmax(t1_preds, axis=1)
pred_y2 = np.argmax(t2_preds, axis=1)
pred_actions = np.argmax(q_preds, axis=1)

print("\n" + "="*60)
print("📊 VISUAL EVALUATION METRICS (CLIENT 1) 📊")
print("="*60)

# 1. RL Decision Matrix
ideal_actions_for_matrix = np.where(aligned_true_bin == 0, 0, 2)
cm_rl = confusion_matrix(ideal_actions_for_matrix, pred_actions, labels=[0, 1, 2, 3])
cm_rl_clean = cm_rl[[0, 2], :]

plt.figure(figsize=(10, 5))
sns.heatmap(cm_rl_clean, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Allow (0)', 'Rate-Limit (1)', 'Drop (2)', 'Req Label (3)'],
            yticklabels=['True Benign (Should Allow)', 'True Attack (Should Drop)'])
plt.title('RL Agent Decision Matrix (Client 1 - Round 50)', fontsize=15, fontweight='bold')
plt.xlabel('Action Selected by DQN Agent', fontsize=12)
plt.ylabel('Ground Truth Category', fontsize=12)
plt.tight_layout()
plt.show()

# 2. SAE Reconstruction
EVAL_LIMIT = min(20000, len(aligned_true_bin))
true_windows = np.array([test_X[i : i + WINDOW_SIZE] for i in range(EVAL_LIMIT)])
pred_windows = sae_preds[:EVAL_LIMIT]
mse_per_window = np.mean(np.square(true_windows - pred_windows), axis=(1, 2))

plt.figure(figsize=(10, 6))
sns.histplot(mse_per_window[aligned_true_bin[:EVAL_LIMIT] == 0], color='green', label='Benign Traffic', kde=True, bins=50, alpha=0.5)
sns.histplot(mse_per_window[aligned_true_bin[:EVAL_LIMIT] == 1], color='red', label='Attack Traffic', kde=True, bins=50, alpha=0.5)
plt.title('Task 4: SAE Reconstruction Error Distribution', fontsize=14, fontweight='bold')
plt.legend()
plt.show()

# 3. Text Metrics Summary
def get_metrics(y_true, y_pred, avg='macro'):
    return {
        'Accuracy' : round(accuracy_score(y_true, y_pred) * 100, 2),
        'F1 Score' : round(f1_score(y_true, y_pred, average=avg, zero_division=0) * 100, 2),
    }

SEP = "=" * 62
t1 = get_metrics(aligned_y1, pred_y1)
print(SEP)
print(f"  Task 1 — Threat Family (6-class) | Acc: {t1['Accuracy']}% | F1: {t1['F1 Score']}%")

attack_mask = aligned_true_bin > 0
t2 = get_metrics(aligned_y2[attack_mask], pred_y2[attack_mask])
print(SEP)
print(f"  Task 2 — Threat Subtype (Attacks) | Acc: {t2['Accuracy']}% | F1: {t2['F1 Score']}%")

mse_t3 = mean_squared_error(aligned_y3, t3_preds.flatten())
print(SEP)
print(f"  Task 3 — Intensity Regression | MSE: {mse_t3:.5f} | RMSE: {np.sqrt(mse_t3):.5f}")

pred_bin_rl = (pred_actions > 0).astype(int)
t4 = get_metrics(aligned_true_bin, pred_bin_rl, avg='binary')
print(SEP)
print(f"  Task 4 — RL Agent Binary IPS Decision | Acc: {t4['Accuracy']}% | F1: {t4['F1 Score']}%")
print(SEP)

import time

print("\n" + "="*80)
print(" 🔍 UPDATED FEATURE IMPORTANCE (PERMUTATION)")
print("="*80)

# Evaluate on a 10,000 window subset to keep calculation time under a few minutes
SUBSET_SIZE = 10000
subset_X = test_X[:SUBSET_SIZE]
subset_true_bin = test_y_bin[WINDOW_SIZE - 1 : SUBSET_SIZE]

# Baseline Accuracy
baseline_states = tf.keras.utils.timeseries_dataset_from_array(
    subset_X, None, sequence_length=WINDOW_SIZE, batch_size=BATCH_SIZE
)

base_q_preds, _, _, _, _ = final_model.predict(baseline_states, verbose=0)
baseline_actions = np.argmax(base_q_preds, axis=1)

ideal_subset_actions = np.where(subset_true_bin == 0, 0, 2)
baseline_accuracy = np.mean(baseline_actions == ideal_subset_actions)

feature_importances = {}
print(f"Baseline IPS Accuracy on Subset: {baseline_accuracy:.4f}\nProcessing feature permutation (this may take a minute)...")

for i, feature_name in enumerate(features_to_keep):
    permuted_X = np.copy(subset_X)
    np.random.shuffle(permuted_X[:, i])

    permuted_states = tf.keras.utils.timeseries_dataset_from_array(
        permuted_X, None, sequence_length=WINDOW_SIZE, batch_size=BATCH_SIZE
    )
    perm_q_preds, _, _, _, _ = final_model.predict(permuted_states, verbose=0)
    permuted_actions = np.argmax(perm_q_preds, axis=1)

    permuted_accuracy = np.mean(permuted_actions == ideal_subset_actions)
    feature_importances[feature_name] = baseline_accuracy - permuted_accuracy

# Sort and Plot Top 15
sorted_importances = sorted(feature_importances.items(), key=lambda x: x[1], reverse=True)
top_features = [x[0] for x in sorted_importances[:15]]
top_scores = [x[1] for x in sorted_importances[:15]]

plt.figure(figsize=(10, 8))
sns.barplot(x=top_scores, y=top_features, palette="magma")
plt.title("Top 15 Driver Features for Threat Mitigation (Client 1)", fontsize=14, fontweight='bold')
plt.xlabel("Decrease in Agent Accuracy when Feature is Corrupted", fontsize=12)
plt.ylabel("Network Feature", fontsize=12)
plt.tight_layout()
plt.show()

print("\n" + "="*80)
print(" 🏆 PERSONALIZED FEDERATED LEARNING: CLIENT SHOWDOWN")
print("="*80)

client_results = []

for i in range(1, 7):
    # Notice the updated filename!
    client_path = os.path.join(MODEL_DIR, f"checkpoint_round_50_client_{i}.keras")

    try:
        # Load each client silently
        c_model = tf.keras.models.load_model(client_path, compile=False)
        c_q_preds, _, _, _, _ = c_model.predict(test_states, verbose=0)

        # Get binary RL predictions (0 = Allow/Benign, >0 = Mitigate/Attack)
        c_actions = np.argmax(c_q_preds, axis=1)
        c_bin_preds = (c_actions > 0).astype(int)

        # Calculate metrics
        acc = accuracy_score(aligned_true_bin, c_bin_preds)
        f1 = f1_score(aligned_true_bin, c_bin_preds, average='binary', zero_division=0)

        # Count Active Learning Requests (Action 3)
        al_requests = np.sum(c_actions == 3)

        client_results.append({
            "Client Node": f"Client {i}",
            "IPS Accuracy (%)": round(acc * 100, 2),
            "F1 Score (%)": round(f1 * 100, 2),
            "Oracle Requests (Active Learning)": al_requests
        })
        print(f"✅ Evaluated Client {i}...")

    except Exception as e:
        print(f"⚠️ Could not load Client {i}: {e}")

# Display the comparison table
showdown_df = pd.DataFrame(client_results)
showdown_df = showdown_df.sort_values(by="IPS Accuracy (%)", ascending=False).reset_index(drop=True)

print("\n📊 CLIENT PERFORMANCE COMPARISON ON GLOBAL TEST SET:")
display(showdown_df)

# Plot the comparison
plt.figure(figsize=(10, 5))
sns.barplot(data=showdown_df, x="Client Node", y="IPS Accuracy (%)", palette="viridis")
plt.title("Federated Client Performance Comparison (Round 50)", fontsize=14, fontweight='bold')
plt.ylim(min(showdown_df["IPS Accuracy (%)"]) - 2, 100) # Dynamic zoom for better visual
for index, row in showdown_df.iterrows():
    plt.text(index, row["IPS Accuracy (%)"] - 1, f"{row['IPS Accuracy (%)']}%", color='white', ha="center", fontweight='bold')
plt.tight_layout()
plt.show()

# ==============================================================================
# 📊 UNIFIED METRICS SUMMARY — ALL TASKS AT A GLANCE (ROUND 50)
# ==============================================================================
import os
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, mean_squared_error
)

# ── CONFIG (Update MODEL_DIR to your Kaggle 50-round results folder) ──────────
MODEL_DIR  = "/kaggle/input/datasets/kankshitha2808/till-50"
TEST_FILE  = "/kaggle/input/datasets/kankshitha2808/multiclass-parquet-dataset/final_test_multiclass.parquet"

# Evaluating Client 1's personalized performance
MODEL_FILE = os.path.join(MODEL_DIR, "checkpoint_round_50_client_1.keras")

WINDOW_SIZE    = 10
BATCH_SIZE     = 512
BENIGN_IDX_T1  = 0
NUM_ACTIONS    = 4   # 0=Allow, 1=Rate-Limit, 2=Drop, 3=Request-Label

label_remapping = {
    0: 0, 1: 1, 2: 2, 3: 2, 4: 3, 5: 3, 6: 4, 7: 5, 8: 5, 9: 5,
    10: 5, 11: 2, 12: 2, 13: 2, 14: 2, 15: 3, 16: 3, 17: 3, 18: 3
}
features_to_keep = [
    'Header_Length', 'Protocol Type', 'Duration', 'IPv', 'LLC',
    'fin_flag_number', 'syn_flag_number', 'rst_flag_number',
    'psh_flag_number', 'ack_flag_number', 'ece_flag_number', 'cwr_flag_number',
    'ack_count', 'syn_count', 'fin_count', 'rst_count', 'HTTP', 'HTTPS', 'DNS',
    'Telnet', 'SMTP', 'SSH', 'IRC', 'TCP', 'UDP', 'DHCP', 'ARP', 'ICMP', 'IGMP',
    'Rate', 'Srate', 'Drate', 'Tot sum', 'Min', 'Max', 'AVG', 'Std',
    'Tot size', 'IAT', 'Number', 'Radius', 'Covariance', 'Variance', 'Weight'
]

# ── LOAD & PREPROCESS TEST DATA ───────────────────────────────────────────────
print("Loading Test Data...")
df_test = pd.read_parquet(TEST_FILE, engine='pyarrow')
df_test = df_test.fillna(df_test.median(numeric_only=True))

y2_raw     = df_test['label'].astype(int).values
test_y1    = np.vectorize(label_remapping.get)(y2_raw)
test_y_bin = (test_y1 > 0).astype(np.int32)
test_y2    = np.where(test_y1 == BENIGN_IDX_T1, -1, y2_raw)
y3_raw     = df_test['Magnitue'].fillna(0.0).values.reshape(-1, 1)
test_y3    = MinMaxScaler().fit_transform(y3_raw).flatten().astype(np.float32)
test_y3    = np.where(test_y1 == BENIGN_IDX_T1, 0.0, test_y3)

test_X = MinMaxScaler().fit_transform(df_test[features_to_keep].values.astype(np.float32))

test_states = tf.keras.utils.timeseries_dataset_from_array(
    test_X, None, sequence_length=WINDOW_SIZE, batch_size=BATCH_SIZE
)

aligned_true_bin = test_y_bin[WINDOW_SIZE - 1:]
aligned_y1       = test_y1[WINDOW_SIZE - 1:]
aligned_y2       = test_y2[WINDOW_SIZE - 1:]
aligned_y3       = test_y3[WINDOW_SIZE - 1:]

# ── LOAD MODEL & RUN INFERENCE ────────────────────────────────────────────────
print(f"Loading 50-Round Model: {MODEL_FILE}")
final_model = tf.keras.models.load_model(MODEL_FILE, compile=False)
q_preds, t1_preds, t2_preds, t3_preds, sae_preds = final_model.predict(test_states)

pred_y1      = np.argmax(t1_preds, axis=1)
pred_y2      = np.argmax(t2_preds, axis=1)
pred_actions = np.argmax(q_preds, axis=1)

# ── HELPER ────────────────────────────────────────────────────────────────────
def metrics(y_true, y_pred, avg='macro'):
    return {
        'Accuracy' : round(accuracy_score(y_true, y_pred) * 100, 2),
        'Precision': round(precision_score(y_true, y_pred, average=avg, zero_division=0) * 100, 2),
        'Recall'   : round(recall_score(y_true, y_pred, average=avg, zero_division=0) * 100, 2),
        'F1 Score' : round(f1_score(y_true, y_pred, average=avg, zero_division=0) * 100, 2),
    }

SEP = "=" * 62

# ── TASK 1 ────────────────────────────────────────────────────────────────────
t1 = metrics(aligned_y1, pred_y1)
print("\n" + SEP)
print("  Task 1 — Threat Family Classification (6-class)")
print("  (Broad attack category: Benign / DoS / Brute-Force / etc.)")
print(SEP)
print(f"  Accuracy  : {t1['Accuracy']} %")
print(f"  Precision : {t1['Precision']} %  (macro-avg)")
print(f"  Recall    : {t1['Recall']} %  (macro-avg)")
print(f"  F1 Score  : {t1['F1 Score']} %  (macro-avg)")

# ── TASK 2 ────────────────────────────────────────────────────────────────────
attack_mask = aligned_true_bin > 0
t2 = metrics(aligned_y2[attack_mask], pred_y2[attack_mask])
print(f"\n{SEP}")
print("  Task 2 — Threat Subtype Classification (19-class, attacks only)")
print("  (Fine-grained attack sub-type identification)")
print(SEP)
print(f"  Accuracy  : {t2['Accuracy']} %")
print(f"  Precision : {t2['Precision']} %  (macro-avg)")
print(f"  Recall    : {t2['Recall']} %  (macro-avg)")
print(f"  F1 Score  : {t2['F1 Score']} %  (macro-avg)")

# ── TASK 3 ────────────────────────────────────────────────────────────────────
mse_t3  = mean_squared_error(aligned_y3, t3_preds.flatten())
rmse_t3 = np.sqrt(mse_t3)
print(f"\n{SEP}")
print("  Task 3 — Attack Intensity Regression (0–1 scaled score)")
print("  (How severe/intense the attack traffic is)")
print(SEP)
print(f"  MSE  (Mean Squared Error)       : {mse_t3:.5f}")
print(f"  RMSE (Root Mean Squared Error)  : {rmse_t3:.5f}")
print("  (Acc / Precision / Recall / F1 not applicable — regression task)")

# ── TASK 4 — RL AGENT IPS (4-action) ─────────────────────────────────────────
# Collapse the 4-action space into binary: 0=Allow → Benign, {1,2,3}=Any Mitigation → Attack
pred_bin_rl = (pred_actions > 0).astype(int)
t4 = metrics(aligned_true_bin, pred_bin_rl, avg='binary')

total      = len(aligned_true_bin)
n_attacks  = np.sum(aligned_true_bin == 1)
n_benign   = np.sum(aligned_true_bin == 0)

# Per-action breakdown
tp_drop      = np.sum((aligned_true_bin == 1) & (pred_actions == 2))   # Attack → Drop ✅
fn_allow     = np.sum((aligned_true_bin == 1) & (pred_actions == 0))   # Attack → Allow ❌
fn_ratelimit = np.sum((aligned_true_bin == 1) & (pred_actions == 1))   # Attack → Rate-Limit ⚠️
al_attack    = np.sum((aligned_true_bin == 1) & (pred_actions == 3))   # Attack → Req. Label 🧠

tn_allow     = np.sum((aligned_true_bin == 0) & (pred_actions == 0))   # Benign → Allow ✅
fp_drop      = np.sum((aligned_true_bin == 0) & (pred_actions == 2))   # Benign → Drop ❌
fp_ratelimit = np.sum((aligned_true_bin == 0) & (pred_actions == 1))   # Benign → Rate-Limit ⚠️
al_benign    = np.sum((aligned_true_bin == 0) & (pred_actions == 3))   # Benign → Req. Label 🧠

print(f"\n{SEP}")
print("  Task 4 — RL Agent IPS Decision (4-Action: Allow / Rate-Limit / Drop / Req-Label)")
print("  (DQN agent deciding how to handle each traffic window)")
print(SEP)
print(f"  [Binary view: Allow=Benign, Mitigate=Attack]")
print(f"  Accuracy  : {t4['Accuracy']} %")
print(f"  Precision : {t4['Precision']} %  (binary, attack = positive class)")
print(f"  Recall    : {t4['Recall']} %  (binary, attack = positive class)")
print(f"  F1 Score  : {t4['F1 Score']} %  (binary, attack = positive class)")

print(f"\n  {'─'*56}")
print(f"  Attack Windows ({n_attacks:,} total)")
print(f"    ✅ Dropped (True Positive)       : {tp_drop:,}  ({tp_drop/max(1,n_attacks)*100:.2f}%)")
print(f"    ❌ Allowed (False Negative)      : {fn_allow:,}  ({fn_allow/max(1,n_attacks)*100:.2f}%)")
print(f"    ⚠️  Rate-Limited (Partial)        : {fn_ratelimit:,}  ({fn_ratelimit/max(1,n_attacks)*100:.2f}%)")
print(f"    🧠 Sent to Oracle (Active Learn) : {al_attack:,}  ({al_attack/max(1,n_attacks)*100:.2f}%)")

print(f"\n  Benign Windows ({n_benign:,} total)")
print(f"    ✅ Allowed (True Negative)       : {tn_allow:,}  ({tn_allow/max(1,n_benign)*100:.2f}%)")
print(f"    ❌ Dropped (False Positive)      : {fp_drop:,}  ({fp_drop/max(1,n_benign)*100:.2f}%)")
print(f"    ⚠️  Rate-Limited (Over-Penalized) : {fp_ratelimit:,}  ({fp_ratelimit/max(1,n_benign)*100:.2f}%)")
print(f"    🧠 Sent to Oracle (Active Learn) : {al_benign:,}  ({al_benign/max(1,n_benign)*100:.2f}%)")

print(f"\n{SEP}\n")

